dns:
  servers:
    - ip: 208.67.222.222
    - ip: 208.67.222.220
hostAliases:
  - ip: 123.123.123.123
    hostnames:
      - my.hostname.one
      - my.hostname.two
  - ip: 12.21.34.43
    hostnames:
      - my.hostname.three
      - my.hostname.four